#ifndef MARKDOWN_CORE_TEST_SUPPORT_H
#define MARKDOWN_CORE_TEST_SUPPORT_H

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include <markdown_core.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Shared native test support for the CTest suites.  Every runner links this
 * library instead of re-implementing fixture, comparison, or failure-report
 * glue.  All
 * verification goes through the read-only markdown_core facade (accessors,
 * canonical AST dump); no renderer is ever invoked.  All comparisons are
 * UTF-8 byte comparisons; all diffs are line-oriented and deterministic. */

#define TS_MAX_TAGS 16

typedef struct ts_spec_case {
    char *markdown;
    size_t markdown_length; /* bytes; the markdown may contain NULs */
    char *expected;
    char *section;
    /* The fence tags after `example`: labels that classify the example
     * for the oracle corpora (`tagged`/`untagged`). They select nothing:
     * every example parses the one dialect. */
    char *tags[TS_MAX_TAGS];
    size_t tag_count;
    int example;
    int start_line;
    int end_line;
} ts_spec_case;

typedef struct ts_spec_file {
    ts_spec_case *cases;
    size_t count;
} ts_spec_file;

/* File IO -------------------------------------------------------------- */

/* Reads a whole file.  Returns NULL on failure.  The buffer is always
 * NUL-terminated one byte past *length. */
uint8_t *ts_read_file(const char *path, size_t *length);

/* Spec fixtures --------------------------------------------------------- */

/* Parses a CommonMark-style spec fixture (32-backtick example fences with a
 * `.` separator).  Examples flagged `disabled` are skipped.  Returns 0 on
 * success. */
int ts_spec_load(const char *path, ts_spec_file *out);
void ts_spec_free(ts_spec_file *file);

/* Traversal -------------------------------------------------------------- */

/* Parses `bytes` through the public facade -- the one language, the one
 * transaction every consumer runs -- and prints the failure's status to
 * stderr and returns NULL on failure. */
markdown_core_document *ts_ast_parse(const uint8_t *bytes, size_t length);

/* A call the test expects to succeed: any other status names the call on
 * stderr and aborts the runner, so no answer is read from an out-parameter
 * the call did not write. */
void ts_require_ok(markdown_core_status status, const char *call);
#define TS_OK(call) ts_require_ok((call), #call)

/* A node-valued field read through its accessor, which must succeed. */
typedef markdown_core_status (*ts_node_field)(const markdown_core_node *node, const markdown_core_node **field);
const markdown_core_node *ts_field(const markdown_core_node *node, ts_node_field accessor);

/* A node's absolute source range in bytes, resolved from the extents by the
 * walk itself rather than by the facade's scope query. */
typedef struct {
    int64_t start, end;
} ts_ast_range;

/* Pre-order callback; return non-zero to abort the walk. */
typedef int (*ts_ast_visit_fn)(const markdown_core_node *node, ts_ast_range range, void *context);

/* Iterative pre-order walk over every owned Markup field in canonical order,
 * rooted at the document root `root`.  Never recurses, so pathologically deep
 * trees are safe.  Returns the first non-zero visitor result, 0 on
 * completion, or -1 on allocation failure. */
int ts_ast_walk(const markdown_core_node *root, ts_ast_visit_fn visit, void *context);

/* Where the walk found a node: its range, the node whose relation holds it
 * (NULL for the root) and that relation's place among the owner's relations
 * in canonical field order, counting absent and empty ones. */
typedef struct {
    ts_ast_range range;
    const markdown_core_node *owner;
    size_t relation;
} ts_ast_place;

typedef int (*ts_ast_owned_visit_fn)(const markdown_core_node *node, ts_ast_place place, void *context);

/* `ts_ast_walk`, telling each node's owner and relation. */
int ts_ast_walk_owned(const markdown_core_node *root, ts_ast_owned_visit_fn visit, void *context);

/* THE FIRST NODE WHOSE RANGE LEAVES ITS SOURCE under `root`, or NULL when
 * every range lies in `[0, length]`.
 *
 * A scan that reads past its line but stays inside the parser's own buffer is
 * invisible to a sanitizer; the range it leaves behind is what shows it. The
 * walk itself can fail on allocation, which also answers NULL. */
const markdown_core_node *ts_ast_range_outside(const markdown_core_node *root, size_t length);

/* Counts every node kind in the subtree.  `counts` must hold
 * TS_KIND_COUNT entries. Returns 0 on success, -1 if traversal fails or a
 * node kind exceeds the counter capacity. */
int ts_ast_count_kinds(const markdown_core_node *root, size_t *counts);
/* BEGIN GENERATED by scripts/tooling/generate-node-kinds.mjs; edit the node-kind schemas instead. */
#define TS_KIND_COUNT (MARKDOWN_CORE_KIND_METADATA + 1)
/* END GENERATED */

/* Concatenates the literals of every Text node in pre-order into a malloc'd
 * NUL-terminated buffer (embedded NULs impossible: parser replaces them). */
char *ts_ast_concat_text(const markdown_core_node *root, size_t *length);

/* Comparison and failure reporting -------------------------------------- */

/* Prints a deterministic line diff between expected and actual to stream. */
void ts_print_line_diff(FILE *stream, const char *expected, const char *actual);

/* Deterministic data ----------------------------------------------------- */

/* xorshift64* PRNG for reproducible fuzz-smoke inputs. */
typedef struct ts_prng {
    uint64_t state;
} ts_prng;

void ts_prng_seed(ts_prng *prng, uint64_t seed);
uint64_t ts_prng_next(ts_prng *prng);

/* Appends `unit` to a growable buffer `count` times.  The buffer is
 * NUL-terminated.  Returns the malloc'd buffer; *length receives the byte
 * length. */
char *ts_repeat(const char *unit, size_t count, size_t *length);

/* Monotonic clock in nanoseconds for relative benchmark measurements. */
uint64_t ts_monotonic_ns(void);

#ifdef __cplusplus
}
#endif

#endif
