// Generated by scripts/tooling/generate-node-kinds.mjs from docs/specs/canonical-ast.json; do not edit.
package com.nouprax.markdown.core

internal enum class WireNodeKind(
    val rawValue: Int,
    /** Whether a `[Markup]` field accepts this kind: no field of the contract names it as its type. */
    val content: Boolean,
) {
    DOCUMENT(1, false),
    CALLOUT(2, true),
    PARAGRAPH(3, true),
    HEADING(4, true),
    THEMATIC_BREAK(5, true),
    LIST(6, true),
    LIST_ITEM(7, false),
    CODE_BLOCK(8, true),
    HTML_BLOCK(9, true),
    FORMULA_BLOCK(10, true),
    TABLE(11, true),
    DIRECTIVE_BLOCK(12, true),
    TEXT(13, true),
    SOFT_BREAK(14, true),
    LINE_BREAK(15, true),
    CODE(16, true),
    HTML(17, true),
    FORMULA(18, true),
    EMPHASIS(19, true),
    STRONG(20, true),
    STRIKETHROUGH(21, true),
    LINK(22, true),
    EMBEDDED(23, true),
    DIRECTIVE(24, true),
    CITE(25, true),
    TABLE_ROW(26, false),
    TABLE_CELL(27, false),
    DIRECTIVE_LABEL(28, false),
    COMMENT(29, true),
    CROSS_LINK(30, true),
    MARK(31, true),
    CROSS_EMBEDDED(32, true),
    INSERTION(33, true),
    SPAN(34, true),
    SUPERSCRIPT(35, true),
    SUBSCRIPT(36, true),
    DEFINITION_LIST(37, true),
    DEFINITION(38, false),
    TABLE_CAPTION(39, false),
    CITATION(40, false),
    FOOTNOTE(41, true),
    SPECIMEN(42, true),
    METADATA(43, false),
    ;

    companion object {
        private val byRawValue = entries.associateBy(WireNodeKind::rawValue)

        fun from(rawValue: Int): WireNodeKind =
            requireNotNull(byRawValue[rawValue]) { "native result contains unknown node kind $rawValue" }
    }
}
