/* registry_runner: the prepared projection of the core registry, as C.
 *
 *   registry_runner --write FILE   generate FILE (elements/core-registry.inc)
 *   registry_runner --check FILE   exit 1 when FILE is not what --write makes
 *
 * The tables are exactly what markdown_core_registry_prepare builds from the
 * core descriptors, spelled as constants so that a parse prepares nothing.
 * An element's symbol is its descriptor name upper-cased:
 * MARKDOWN_CORE_ELEMENT_<NAME>. The api tests hold the committed file to the
 * builder; run --write again when a descriptor's bytes or hooks change. */
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "element.h"
#include "markdown-core-elements.h"
#include "parser.h"

static void put_symbol(FILE *out, const markdown_core_element *element) {
    fputs("&MARKDOWN_CORE_ELEMENT_", out);
    for (const char *c = element->name; *c; c++) {
        fputc(toupper((unsigned char)*c), out);
    }
}

static void put_byte_comment(FILE *out, unsigned char c) {
    if (c > 32 && c < 127 && c != '\'' && c != '\\' && c != '*' && c != '/') {
        fprintf(out, " /* '%c' */", c);
    } else {
        fprintf(out, " /* 0x%02x */", c);
    }
}

static void put_byte_set(FILE *out, const char *name, const int8_t *set) {
    fprintf(out, "static const int8_t %s[256] = {", name);
    for (size_t c = 0; c < 256; c++) {
        fprintf(out, "%s%d,", c % 32 ? " " : "\n    ", set[c]);
    }
    fputs("\n};\n\n", out);
}

static int emit(FILE *out) {
    size_t count;
    const markdown_core_element *const *elements = markdown_core_core_elements(&count);
    markdown_core_registry registry;
    if (!markdown_core_registry_prepare(markdown_core_get_default_mem_allocator(), elements, count, NULL, &registry)) {
        return 0;
    }
    fputs("/* Generated by registry_runner --write from the core element descriptors;\n"
          " * do not edit. Included by core-elements.c after CORE_ELEMENTS: the\n"
          " * projection markdown_core_registry_prepare would build of them, prepared\n"
          " * once, which every parse borrows (see markdown_core_registry). */\n\n",
          out);

    fputs("static const size_t CORE_INLINE_DISPATCH_OFFSETS[257] = {", out);
    for (size_t c = 0; c < 257; c++) {
        fprintf(out, "%s%zu,", c % 16 ? " " : "\n    ", registry.inline_dispatch_offsets[c]);
    }
    fputs("\n};\n\n", out);

    size_t candidates = registry.inline_dispatch_offsets[256];
    if (candidates) {
        fprintf(out, "static const markdown_core_inline_candidate CORE_INLINE_DISPATCH[%zu] = {\n", candidates);
        for (size_t c = 0; c < 256; c++) {
            for (size_t i = registry.inline_dispatch_offsets[c]; i < registry.inline_dispatch_offsets[c + 1]; i++) {
                const markdown_core_inline_candidate *candidate = &registry.inline_dispatch[i];
                fputs("    {", out);
                put_symbol(out, candidate->element);
                fprintf(out, ", %s, %s},", candidate->dispatches ? "true" : "false",
                        candidate->terminates ? "true" : "false");
                put_byte_comment(out, (unsigned char)c);
                fputc('\n', out);
            }
        }
        fputs("};\n\n", out);
    } else {
        fputs("static const markdown_core_inline_candidate *const CORE_INLINE_DISPATCH = NULL;\n\n", out);
    }

    if (registry.block_owner_count) {
        fprintf(out, "static const markdown_core_element *const CORE_BLOCK_OWNERS[%zu] = {\n",
                registry.block_owner_count);
        for (size_t i = 0; i < registry.block_owner_count; i++) {
            fputs("    ", out);
            put_symbol(out, registry.block_owners[i]);
            fputs(",\n", out);
        }
        fputs("};\n\n", out);
    } else {
        fputs("static const markdown_core_element *const *const CORE_BLOCK_OWNERS = NULL;\n\n", out);
    }
    static const char *const SET_NAMES[4] = {"SCAN", "INTERRUPT", "OPEN", "PARAGRAPH"};
    const uint64_t *sets[4] = {registry.block_owner_sets.scan, registry.block_owner_sets.interrupt,
                               registry.block_owner_sets.open, registry.block_owner_sets.paragraph};
    size_t words = registry.block_owner_sets.words;
    fprintf(out,
            "/* By first byte, a bit per block owner above, %zu word%s per byte: the\n"
            " * owners each block-start arbitration loop visits. */\n",
            words, words == 1 ? "" : "s");
    for (size_t hook = 0; hook < 4; hook++) {
        fprintf(out, "static const uint64_t CORE_BLOCK_%s_OWNERS[%zu] = {", SET_NAMES[hook], 256 * words);
        for (size_t c = 0; c < 256 * words; c++) {
            fprintf(out, "%sUINT64_C(0x%llx),", c % 4 ? " " : "\n    ", (unsigned long long)sets[hook][c]);
        }
        fputs("\n};\n\n", out);
    }

    const markdown_core_inline_hooks *hooks = &registry.inline_hooks;
    size_t hook_count = hooks->init_count + hooks->finish_count + hooks->dispose_count;
    if (hook_count) {
        fprintf(out, "/* init_inline x%zu, then finish_inline x%zu, then dispose_inline x%zu. */\n", hooks->init_count,
                hooks->finish_count, hooks->dispose_count);
        fprintf(out, "static const markdown_core_element *const CORE_INLINE_HOOKS[%zu] = {\n", hook_count);
        for (size_t i = 0; i < hook_count; i++) {
            fputs("    ", out);
            put_symbol(out, hooks->elements[i]);
            fputs(",\n", out);
        }
        fputs("};\n\n", out);
    } else {
        fputs("static const markdown_core_element *const *const CORE_INLINE_HOOKS = NULL;\n\n", out);
    }

    put_byte_set(out, "CORE_SPECIAL_CHARS", registry.special_chars);
    put_byte_set(out, "CORE_SKIP_CHARS", registry.skip_chars);

    fputs("static const markdown_core_registry CORE_REGISTRY = {\n"
          "    .elements = CORE_ELEMENTS,\n"
          "    .element_count = CORE_ELEMENT_COUNT,\n",
          out);
    fputs("    .text_structure = ", out);
    if (registry.text_structure) {
        put_symbol(out, registry.text_structure);
    } else {
        fputs("NULL", out);
    }
    fputs(",\n    .delimiter_owners =\n        {\n", out);
    for (size_t rule = 0; rule < MARKDOWN_CORE_DELIM_RULE_COUNT; rule++) {
        if (registry.delimiter_owners[rule]) {
            fprintf(out, "            [%zu] = ", rule);
            put_symbol(out, registry.delimiter_owners[rule]);
            fputs(",\n", out);
        }
    }
    fputs("        },\n", out);
    fputs("    .inline_dispatch_offsets = CORE_INLINE_DISPATCH_OFFSETS,\n"
          "    .inline_dispatch = CORE_INLINE_DISPATCH,\n"
          "    .block_owners = CORE_BLOCK_OWNERS,\n",
          out);
    fprintf(out, "    .block_owner_count = %zu,\n", registry.block_owner_count);
    fprintf(out,
            "    .block_owner_sets = {CORE_BLOCK_SCAN_OWNERS, CORE_BLOCK_INTERRUPT_OWNERS, CORE_BLOCK_OPEN_OWNERS,\n"
            "                         CORE_BLOCK_PARAGRAPH_OWNERS, %zu},\n",
            words);
    fprintf(out, "    .inline_hooks = {CORE_INLINE_HOOKS, %zu, %zu, %zu},\n", hooks->init_count, hooks->finish_count,
            hooks->dispose_count);
    fputs("    .special_chars = CORE_SPECIAL_CHARS,\n"
          "    .skip_chars = CORE_SKIP_CHARS,\n"
          "    .storage = NULL,\n"
          "};\n",
          out);
    markdown_core_registry_release(markdown_core_get_default_mem_allocator(), &registry);
    return !ferror(out);
}

static char *read_all(FILE *file, size_t *length) {
    size_t capacity = 4096, size = 0;
    char *data = malloc(capacity);
    while (data) {
        size_t got = fread(data + size, 1, capacity - size, file);
        size += got;
        if (got == 0) {
            break;
        }
        if (size == capacity) {
            capacity *= 2;
            char *grown = realloc(data, capacity);
            if (!grown) {
                free(data);
                return NULL;
            }
            data = grown;
        }
    }
    *length = size;
    return data;
}

int main(int argc, char **argv) {
    if (argc != 3 || (strcmp(argv[1], "--write") != 0 && strcmp(argv[1], "--check") != 0)) {
        fputs("usage: registry_runner (--write | --check) FILE\n", stderr);
        return 2;
    }
    FILE *generated = tmpfile();
    if (!generated || !emit(generated)) {
        fputs("registry_runner: could not project the core registry\n", stderr);
        return 1;
    }
    rewind(generated);
    size_t generated_length;
    char *text = read_all(generated, &generated_length);
    fclose(generated);
    if (!text) {
        return 1;
    }
    int status = 0;
    if (strcmp(argv[1], "--write") == 0) {
        FILE *out = fopen(argv[2], "wb");
        if (!out || fwrite(text, 1, generated_length, out) != generated_length || fclose(out) != 0) {
            fprintf(stderr, "registry_runner: cannot write %s\n", argv[2]);
            status = 1;
        } else {
            printf("registry_runner: wrote %s (%zu bytes)\n", argv[2], generated_length);
        }
    } else {
        FILE *in = fopen(argv[2], "rb");
        size_t current_length = 0;
        char *current = in ? read_all(in, &current_length) : NULL;
        if (in) {
            fclose(in);
        }
        if (!current || current_length != generated_length || memcmp(current, text, generated_length) != 0) {
            fprintf(stderr,
                    "registry_runner: %s is not the projection of the core descriptors;\n"
                    "regenerate it with: registry_runner --write %s\n",
                    argv[2], argv[2]);
            status = 1;
        } else {
            printf("registry_runner: %s matches the core descriptors\n", argv[2]);
        }
        free(current);
    }
    free(text);
    return status;
}
