/* Generated by re2c 4.6 */
#include "autolink_scanners.h"
#include <string.h>

/* Shared byte-scanner configuration and lexical primitives. */





/* The grammar's bounded repeats -- a scheme of 2..32 bytes, domain labels
 * of 1..63 -- are length checks on the recognized span, not DFA states:
 * scheme bytes exclude `:`, so the scheme ends at the first colon, and a
 * domain label ends at a dot or at the closing `>`. */
static bufsize_t autolink_scheme_length_ok(const unsigned char *input, size_t end)
{
  const unsigned char *colon = (const unsigned char *)memchr(input, ':', end);
  size_t length = (size_t)(colon - input);
  return length >= 2 && length <= 32;
}

static bufsize_t autolink_labels_ok(const unsigned char *input, size_t end)
{
  const unsigned char *at = (const unsigned char *)memchr(input, '@', end) + 1;
  const unsigned char *limit = input + end - 1;
  while (at < limit) {
    const unsigned char *dot = (const unsigned char *)memchr(at, '.', (size_t)(limit - at));
    const unsigned char *label_end = dot ? dot : limit;
    if (label_end - at > 63) {
      return 0;
    }
    at = label_end + 1;
  }
  return 1;
}



bufsize_t scan_autolink_uri(const unsigned char *data, bufsize_t length, bufsize_t offset)
{
  if (!data || offset < 0 || offset >= length) {
    return 0;
  }
  const unsigned char *input = data + offset;
  size_t p = 0, remaining = (size_t)(length - offset);
  size_t marker = 0;
  size_t start = p;

{
	unsigned char yych;
	static const unsigned char yybm[256] = {
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 192, 128, 192, 192, 128,
		192, 192, 192, 192, 192, 192, 192, 192,
		192, 192, 128, 128,   0, 128,   0, 128,
		128, 192, 192, 192, 192, 192, 192, 192,
		192, 192, 192, 192, 192, 192, 192, 192,
		192, 192, 192, 192, 192, 192, 192, 192,
		192, 192, 192, 128, 128, 128, 128, 128,
		128, 192, 192, 192, 192, 192, 192, 192,
		192, 192, 192, 192, 192, 192, 192, 192,
		192, 192, 192, 192, 192, 192, 192, 192,
		192, 192, 192, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128
	};
	yych = (p < remaining ? input[p] : 0);
	if (yych <= '@') goto yy1;
	if (yych <= 'Z') goto yy3;
	if (yych <= '`') goto yy1;
	if (yych <= 'z') goto yy3;
yy1:
	++p;
yy2:
	{ return 0; }
yy3:
	++p;
	marker = p;
	yych = (p < remaining ? input[p] : 0);
	if (yych <= '/') {
		if (yych <= '+') {
			if (yych <= '*') goto yy2;
			goto yy5;
		} else {
			if (yych <= ',') goto yy2;
			if (yych <= '.') goto yy5;
			goto yy2;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy5;
			if (yych <= '@') goto yy2;
			goto yy5;
		} else {
			if (yych <= '`') goto yy2;
			if (yych <= 'z') goto yy5;
			goto yy2;
		}
	}
yy4:
	++p;
	yych = (p < remaining ? input[p] : 0);
yy5:
	if (yybm[0+yych] & 64) goto yy4;
	if (yych <= '/') goto yy6;
	if (yych <= ':') goto yy7;
yy6:
	p = marker;
	goto yy2;
yy7:
	++p;
	yych = (p < remaining ? input[p] : 0);
	if (yybm[0+yych] & 128) goto yy7;
	if (yych <= '<') goto yy6;
	++p;
	{ return autolink_scheme_length_ok(input, p) ? (bufsize_t)(p - start) : 0; }
}

}

bufsize_t scan_autolink_email(const unsigned char *data, bufsize_t length, bufsize_t offset)
{
  if (!data || offset < 0 || offset >= length) {
    return 0;
  }
  const unsigned char *input = data + offset;
  size_t p = 0, remaining = (size_t)(length - offset);
  size_t marker = 0;
  size_t start = p;

{
	unsigned char yych;
	static const unsigned char yybm[256] = {
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,  32,   0,  32,  32,  32,  32,  32,
		  0,   0,  32,  32,   0, 160,  32,  32,
		 96,  96,  96,  96,  96,  96,  96,  96,
		 96,  96,   0,   0,   0,  32,   0,  32,
		  0,  96,  96,  96,  96,  96,  96,  96,
		 96,  96,  96,  96,  96,  96,  96,  96,
		 96,  96,  96,  96,  96,  96,  96,  96,
		 96,  96,  96,   0,   0,   0,  32,  32,
		 32,  96,  96,  96,  96,  96,  96,  96,
		 96,  96,  96,  96,  96,  96,  96,  96,
		 96,  96,  96,  96,  96,  96,  96,  96,
		 96,  96,  96,  32,  32,  32,  32,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0
	};
	yych = (p < remaining ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= '\'') {
			if (yych == '!') goto yy11;
			if (yych >= '#') goto yy11;
		} else {
			if (yych <= ')') goto yy9;
			if (yych != ',') goto yy11;
		}
	} else {
		if (yych <= '?') {
			if (yych == '=') goto yy11;
			if (yych >= '?') goto yy11;
		} else {
			if (yych <= 'Z') {
				if (yych >= 'A') goto yy11;
			} else {
				if (yych <= ']') goto yy9;
				if (yych <= '~') goto yy11;
			}
		}
	}
yy9:
	++p;
yy10:
	{ return 0; }
yy11:
	++p;
	marker = p;
	yych = (p < remaining ? input[p] : 0);
	if (yych <= ',') {
		if (yych <= '"') {
			if (yych == '!') goto yy13;
			goto yy10;
		} else {
			if (yych <= '\'') goto yy13;
			if (yych <= ')') goto yy10;
			if (yych <= '+') goto yy13;
			goto yy10;
		}
	} else {
		if (yych <= '>') {
			if (yych <= '9') goto yy13;
			if (yych == '=') goto yy13;
			goto yy10;
		} else {
			if (yych <= 'Z') goto yy13;
			if (yych <= ']') goto yy10;
			if (yych <= '~') goto yy13;
			goto yy10;
		}
	}
yy12:
	++p;
	yych = (p < remaining ? input[p] : 0);
yy13:
	if (yybm[0+yych] & 32) goto yy12;
	if (yych <= '>') goto yy14;
	if (yych <= '@') goto yy15;
yy14:
	p = marker;
	goto yy10;
yy15:
	++p;
	yych = (p < remaining ? input[p] : 0);
	if (yybm[0+yych] & 64) goto yy16;
	goto yy14;
yy16:
	++p;
	yych = (p < remaining ? input[p] : 0);
	if (yybm[0+yych] & 128) goto yy17;
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy14;
			goto yy15;
		} else {
			if (yych <= '/') goto yy14;
			if (yych <= '9') goto yy16;
			goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy18;
			if (yych <= '@') goto yy14;
			goto yy16;
		} else {
			if (yych <= '`') goto yy14;
			if (yych <= 'z') goto yy16;
			goto yy14;
		}
	}
yy17:
	++p;
	yych = (p < remaining ? input[p] : 0);
	if (yybm[0+yych] & 128) goto yy17;
	if (yych <= '@') {
		if (yych <= '/') goto yy14;
		if (yych <= '9') goto yy16;
		goto yy14;
	} else {
		if (yych <= 'Z') goto yy16;
		if (yych <= '`') goto yy14;
		if (yych <= 'z') goto yy16;
		goto yy14;
	}
yy18:
	++p;
	{ return autolink_labels_ok(input, p) ? (bufsize_t)(p - start) : 0; }
}

}
