/* Generated by re2c 4.6 */
#include "table_scanners.h"

/* Shared byte-scanner configuration and lexical primitives. */








bufsize_t scan_table_start(const unsigned char *data, bufsize_t length, bufsize_t offset)
{
  if (!data || offset < 0 || offset >= length) {
    return 0;
  }
  const unsigned char *input = data + offset;
  size_t p = 0, remaining = (size_t)(length - offset);
  size_t marker = 0;
  size_t start = p;

{
  unsigned char yych;
  static const unsigned char yybm[256] = {
      0,   0,   0,   0,   0,   0,   0,   0,
      0,  64,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     64,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0, 128,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0
  };
  yych = (p < remaining ? input[p] : 0);
  if (yych <= ',') {
    if (yych <= '\t') {
      if (yych >= '\t') goto yy2;
    } else {
      if (yych == ' ') goto yy2;
    }
  } else {
    if (yych <= ':') {
      if (yych <= '-') goto yy3;
      if (yych >= ':') goto yy4;
    } else {
      if (yych == '|') goto yy2;
    }
  }
  ++p;
yy1:
  { return 0; }
yy2:
  ++p;
  marker = p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 64) goto yy5;
  if (yych == '-') goto yy7;
  if (yych == ':') goto yy8;
  goto yy1;
yy3:
  ++p;
  marker = p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 128) goto yy7;
  if (yych <= 0x1F) {
    if (yych <= '\n') {
      if (yych <= 0x08) goto yy1;
      goto yy10;
    } else {
      if (yych == '\r') goto yy10;
      goto yy1;
    }
  } else {
    if (yych <= ':') {
      if (yych <= ' ') goto yy10;
      if (yych <= '9') goto yy1;
      goto yy9;
    } else {
      if (yych == '|') goto yy10;
      goto yy1;
    }
  }
yy4:
  ++p;
  marker = p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 128) goto yy7;
  goto yy1;
yy5:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 64) goto yy5;
  if (yych == '-') goto yy7;
  if (yych == ':') goto yy8;
yy6:
  p = marker;
  goto yy1;
yy7:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 128) goto yy7;
  if (yych <= 0x1F) {
    if (yych <= '\n') {
      if (yych <= 0x08) goto yy6;
      if (yych <= '\t') goto yy9;
      goto yy11;
    } else {
      if (yych == '\r') goto yy13;
      goto yy6;
    }
  } else {
    if (yych <= ':') {
      if (yych <= ' ') goto yy9;
      if (yych <= '9') goto yy6;
      goto yy9;
    } else {
      if (yych == '|') goto yy14;
      goto yy6;
    }
  }
yy8:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 128) goto yy7;
  goto yy6;
yy9:
  ++p;
  yych = (p < remaining ? input[p] : 0);
yy10:
  if (yych <= '\r') {
    if (yych <= '\t') {
      if (yych <= 0x08) goto yy6;
      goto yy9;
    } else {
      if (yych <= '\n') goto yy11;
      if (yych <= '\f') goto yy6;
      goto yy13;
    }
  } else {
    if (yych <= ' ') {
      if (yych <= 0x1F) goto yy6;
      goto yy9;
    } else {
      if (yych == '|') goto yy14;
      goto yy6;
    }
  }
yy11:
  ++p;
yy12:
  {
      return (bufsize_t)(p - start);
    }
yy13:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yych == '\n') goto yy11;
  goto yy12;
yy14:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 128) goto yy7;
  if (yych <= '\r') {
    if (yych <= '\t') {
      if (yych <= 0x08) goto yy6;
      goto yy14;
    } else {
      if (yych <= '\n') goto yy11;
      if (yych <= '\f') goto yy6;
      goto yy13;
    }
  } else {
    if (yych <= ' ') {
      if (yych <= 0x1F) goto yy6;
      goto yy14;
    } else {
      if (yych == ':') goto yy8;
      goto yy6;
    }
  }
}

}

bufsize_t scan_table_cell(const unsigned char *data, bufsize_t length, bufsize_t offset)
{
  if (!data || offset < 0 || offset >= length) {
    return 0;
  }
  const unsigned char *input = data + offset;
  size_t p = 0, remaining = (size_t)(length - offset);
  size_t start = p;

{
  unsigned char yych;
  static const unsigned char yybm[256] = {
      0,  64,  64,  64,  64,  64,  64,  64,
     64,  64,   0,  64,  64,   0,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64, 128,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,   0,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64,
     64,  64,  64,  64,  64,  64,  64,  64
  };
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 64) goto yy17;
  if (yych <= '\r') goto yy16;
  if (yych <= '\\') goto yy19;
yy16:
  ++p;
  { return 0; }
yy17:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 64) goto yy17;
  if (yych <= '\r') goto yy18;
  if (yych <= '\\') goto yy19;
yy18:
  { return (bufsize_t)(p - start); }
yy19:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 128) goto yy19;
  if (yych <= '\n') {
    if (yych <= 0x00) goto yy18;
    if (yych <= '\t') goto yy17;
    goto yy18;
  } else {
    if (yych == '\r') goto yy18;
    goto yy17;
  }
}

}

bufsize_t scan_table_cell_end(const unsigned char *data, bufsize_t length, bufsize_t offset)
{
  if (!data || offset < 0 || offset >= length) {
    return 0;
  }
  const unsigned char *input = data + offset;
  size_t p = 0, remaining = (size_t)(length - offset);
  size_t start = p;

{
  unsigned char yych;
  static const unsigned char yybm[256] = {
      0,   0,   0,   0,   0,   0,   0,   0,
      0, 128,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    128,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0
  };
  yych = (p < remaining ? input[p] : 0);
  if (yych == '|') goto yy21;
  ++p;
  { return 0; }
yy21:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 128) goto yy21;
  { return (bufsize_t)(p - start); }
}

}

bufsize_t scan_table_row_end(const unsigned char *data, bufsize_t length, bufsize_t offset)
{
  if (!data || offset < 0 || offset >= length) {
    return 0;
  }
  const unsigned char *input = data + offset;
  size_t p = 0, remaining = (size_t)(length - offset);
  size_t marker = 0;
  size_t start = p;

{
  unsigned char yych;
  static const unsigned char yybm[256] = {
      0,   0,   0,   0,   0,   0,   0,   0,
      0, 128,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    128,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0
  };
  yych = (p < remaining ? input[p] : 0);
  if (yych <= '\f') {
    if (yych <= 0x08) goto yy23;
    if (yych <= '\t') goto yy25;
    if (yych <= '\n') goto yy26;
  } else {
    if (yych <= '\r') goto yy28;
    if (yych == ' ') goto yy25;
  }
yy23:
  ++p;
yy24:
  { return 0; }
yy25:
  ++p;
  marker = p;
  yych = (p < remaining ? input[p] : 0);
  if (yych <= '\f') {
    if (yych <= 0x08) goto yy24;
    if (yych <= '\n') goto yy30;
    goto yy24;
  } else {
    if (yych <= '\r') goto yy30;
    if (yych == ' ') goto yy30;
    goto yy24;
  }
yy26:
  ++p;
yy27:
  { return (bufsize_t)(p - start); }
yy28:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yych == '\n') goto yy26;
  goto yy27;
yy29:
  ++p;
  yych = (p < remaining ? input[p] : 0);
yy30:
  if (yybm[0+yych] & 128) goto yy29;
  if (yych <= 0x08) goto yy31;
  if (yych <= '\n') goto yy26;
  if (yych == '\r') goto yy28;
yy31:
  p = marker;
  goto yy24;
}

}

int scan_table_dash(const unsigned char **cursor, const unsigned char *limit,
                     const unsigned char **from)
{
    const unsigned char *input = *cursor;
    size_t p = 0, remaining = (size_t)(limit - input);
    for (;;) {
        size_t start = p;

{
  unsigned char yych;
  static const unsigned char yybm[256] = {
      0,   0,   0,   0,   0,   0,   0,   0,
      0,  64,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     64,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0, 128,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0
  };
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 64) goto yy35;
  if (yych <= 0x00) goto yy33;
  if (yych == '-') goto yy36;
  goto yy34;
yy33:
  ++p;
  { *cursor = input + (p < remaining ? p : remaining); return start == remaining ? 0 : -1; }
yy34:
  ++p;
  { *cursor = input + p; return -1; }
yy35:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 64) goto yy35;
  { continue; }
yy36:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 128) goto yy36;
  { *from = input + start; *cursor = input + p; return 1; }
}

    }
}

int scan_table_horizontal(const unsigned char *data, bufsize_t length, bufsize_t offset)
{
  if (!data || offset < 0 || offset >= length) {
    return 0;
  }
  const unsigned char *input = data + offset;
  size_t p = 0, remaining = (size_t)(length - offset);
    size_t marker = 0;

{
  unsigned char yych;
  static const unsigned char yybm[256] = {
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,  32,   0,  64,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0, 128,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0
  };
  yych = (p < remaining ? input[p] : 0);
  if (yych == '+') goto yy39;
  ++p;
yy38:
  { return 0; }
yy39:
  ++p;
  marker = p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 64) goto yy42;
  if (yych <= '9') {
    if (yych != '+') goto yy38;
  } else {
    if (yych <= ':') goto yy40;
    if (yych == '=') goto yy43;
    goto yy38;
  }
yy40:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 32) goto yy40;
  if (yych == '-') goto yy42;
  if (yych == '=') goto yy43;
yy41:
  p = marker;
  goto yy38;
yy42:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 64) goto yy42;
  if (yych == '+') goto yy44;
  if (yych == ':') goto yy45;
  goto yy41;
yy43:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 128) goto yy43;
  if (yych == '+') goto yy46;
  if (yych == ':') goto yy47;
  goto yy41;
yy44:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 64) goto yy42;
  if (yych <= '+') {
    if (yych <= 0x00) goto yy48;
    if (yych <= '*') goto yy41;
    goto yy44;
  } else {
    if (yych != ':') goto yy41;
  }
yy45:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yych == '+') goto yy49;
  goto yy41;
yy46:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yybm[0+yych] & 128) goto yy43;
  if (yych <= '+') {
    if (yych <= 0x00) goto yy50;
    if (yych <= '*') goto yy41;
    goto yy46;
  } else {
    if (yych != ':') goto yy41;
  }
yy47:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yych == '+') goto yy51;
  goto yy41;
yy48:
  ++p;
  p += -1;
  { return p == remaining ? '-' : 0; }
yy49:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yych <= 0x00) goto yy48;
  goto yy41;
yy50:
  ++p;
  p += -1;
  { return p == remaining ? '=' : 0; }
yy51:
  ++p;
  yych = (p < remaining ? input[p] : 0);
  if (yych <= 0x00) goto yy50;
  goto yy41;
}

}
