/* Generated by re2c 4.6 */
#include "autolink_scanners.h"








bufsize_t _scan_scheme(const unsigned char *input, const unsigned char *limit)
{
  size_t p = 0, length = (size_t)(limit - input);
  size_t marker = 0;
  size_t start = p;

{
	unsigned char yych;
	yych = (p < length ? input[p] : 0);
	if (yych <= '@') goto yy1;
	if (yych <= 'Z') goto yy3;
	if (yych <= '`') goto yy1;
	if (yych <= 'z') goto yy3;
yy1:
	++p;
yy2:
	{ return 0; }
yy3:
	++p;
	marker = p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '/') {
		if (yych <= '+') {
			if (yych <= '*') goto yy2;
		} else {
			if (yych <= ',') goto yy2;
			if (yych >= '/') goto yy2;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '9') goto yy4;
			if (yych <= '@') goto yy2;
		} else {
			if (yych <= '`') goto yy2;
			if (yych >= '{') goto yy2;
		}
	}
yy4:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych == '+') goto yy6;
		} else {
			if (yych != '/') goto yy6;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych >= 'A') goto yy6;
		} else {
			if (yych <= '`') goto yy5;
			if (yych <= 'z') goto yy6;
		}
	}
yy5:
	p = marker;
	goto yy2;
yy6:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych == '+') goto yy8;
			goto yy5;
		} else {
			if (yych == '/') goto yy5;
			goto yy8;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
			goto yy8;
		} else {
			if (yych <= '`') goto yy5;
			if (yych <= 'z') goto yy8;
			goto yy5;
		}
	}
yy7:
	++p;
	{ return (bufsize_t)(p - start); }
yy8:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy5;
		} else {
			if (yych == '/') goto yy5;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy7;
			if (yych <= '@') goto yy5;
		} else {
			if (yych <= '`') goto yy5;
			if (yych >= '{') goto yy5;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych == ':') goto yy7;
	goto yy5;
}

}

bufsize_t _scan_autolink_uri(const unsigned char *input, const unsigned char *limit)
{
  size_t p = 0, length = (size_t)(limit - input);
  size_t marker = 0;
  size_t start = p;

{
	unsigned char yych;
	static const unsigned char yybm[256] = {
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128,   0, 128,   0, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128
	};
	yych = (p < length ? input[p] : 0);
	if (yych <= '@') goto yy10;
	if (yych <= 'Z') goto yy12;
	if (yych <= '`') goto yy10;
	if (yych <= 'z') goto yy12;
yy10:
	++p;
yy11:
	{ return 0; }
yy12:
	++p;
	marker = p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '/') {
		if (yych <= '+') {
			if (yych <= '*') goto yy11;
		} else {
			if (yych <= ',') goto yy11;
			if (yych >= '/') goto yy11;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '9') goto yy13;
			if (yych <= '@') goto yy11;
		} else {
			if (yych <= '`') goto yy11;
			if (yych >= '{') goto yy11;
		}
	}
yy13:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych == '+') goto yy15;
		} else {
			if (yych != '/') goto yy15;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych >= 'A') goto yy15;
		} else {
			if (yych <= '`') goto yy14;
			if (yych <= 'z') goto yy15;
		}
	}
yy14:
	p = marker;
	goto yy11;
yy15:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych == '+') goto yy17;
			goto yy14;
		} else {
			if (yych == '/') goto yy14;
			goto yy17;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
			goto yy17;
		} else {
			if (yych <= '`') goto yy14;
			if (yych <= 'z') goto yy17;
			goto yy14;
		}
	}
yy16:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yybm[0+yych] & 128) goto yy16;
	if (yych <= '<') goto yy14;
	goto yy18;
yy17:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych == '+') goto yy19;
			goto yy14;
		} else {
			if (yych == '/') goto yy14;
			goto yy19;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
			goto yy19;
		} else {
			if (yych <= '`') goto yy14;
			if (yych <= 'z') goto yy19;
			goto yy14;
		}
	}
yy18:
	++p;
	{ return (bufsize_t)(p - start); }
yy19:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= ',') {
			if (yych != '+') goto yy14;
		} else {
			if (yych == '/') goto yy14;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= ':') goto yy16;
			if (yych <= '@') goto yy14;
		} else {
			if (yych <= '`') goto yy14;
			if (yych >= '{') goto yy14;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych == ':') goto yy16;
	goto yy14;
}

}

bufsize_t _scan_autolink_email(const unsigned char *input, const unsigned char *limit)
{
  size_t p = 0, length = (size_t)(limit - input);
  size_t marker = 0;
  size_t start = p;

{
	unsigned char yych;
	static const unsigned char yybm[256] = {
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0, 128,   0, 128, 128, 128, 128, 128,
		  0,   0, 128, 128,   0, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128,   0,   0,   0, 128,   0, 128,
		  0, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128,   0,   0,   0, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128, 128,
		128, 128, 128, 128, 128, 128, 128,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0,
		  0,   0,   0,   0,   0,   0,   0,   0
	};
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych <= '\'') {
			if (yych == '!') goto yy23;
			if (yych >= '#') goto yy23;
		} else {
			if (yych <= ')') goto yy21;
			if (yych != ',') goto yy23;
		}
	} else {
		if (yych <= '?') {
			if (yych == '=') goto yy23;
			if (yych >= '?') goto yy23;
		} else {
			if (yych <= 'Z') {
				if (yych >= 'A') goto yy23;
			} else {
				if (yych <= ']') goto yy21;
				if (yych <= '~') goto yy23;
			}
		}
	}
yy21:
	++p;
yy22:
	{ return 0; }
yy23:
	++p;
	marker = p;
	yych = (p < length ? input[p] : 0);
	if (yych <= ',') {
		if (yych <= '"') {
			if (yych == '!') goto yy25;
			goto yy22;
		} else {
			if (yych <= '\'') goto yy25;
			if (yych <= ')') goto yy22;
			if (yych <= '+') goto yy25;
			goto yy22;
		}
	} else {
		if (yych <= '>') {
			if (yych <= '9') goto yy25;
			if (yych == '=') goto yy25;
			goto yy22;
		} else {
			if (yych <= 'Z') goto yy25;
			if (yych <= ']') goto yy22;
			if (yych <= '~') goto yy25;
			goto yy22;
		}
	}
yy24:
	++p;
	yych = (p < length ? input[p] : 0);
yy25:
	if (yybm[0+yych] & 128) goto yy24;
	if (yych <= '>') goto yy26;
	if (yych <= '@') goto yy27;
yy26:
	p = marker;
	goto yy22;
yy27:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '@') {
		if (yych <= '/') goto yy26;
		if (yych >= ':') goto yy26;
	} else {
		if (yych <= 'Z') goto yy28;
		if (yych <= '`') goto yy26;
		if (yych >= '{') goto yy26;
	}
yy28:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy29;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy29;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy29;
			goto yy26;
		}
	}
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy31;
		if (yych <= '/') goto yy26;
		goto yy32;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy32;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy32;
			goto yy26;
		}
	}
yy29:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych <= '-') goto yy31;
			goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy32;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy32;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy32;
			goto yy26;
		}
	}
yy30:
	++p;
	{ return (bufsize_t)(p - start); }
yy31:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy33;
		if (yych <= '/') goto yy26;
		goto yy34;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy34;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy34;
			goto yy26;
		}
	}
yy32:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy34;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy34;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy34;
			goto yy26;
		}
	}
yy33:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy35;
		if (yych <= '/') goto yy26;
		goto yy36;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy36;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy36;
			goto yy26;
		}
	}
yy34:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy36;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy36;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy36;
			goto yy26;
		}
	}
yy35:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy37;
		if (yych <= '/') goto yy26;
		goto yy38;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy38;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy38;
			goto yy26;
		}
	}
yy36:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy38;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy38;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy38;
			goto yy26;
		}
	}
yy37:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy39;
		if (yych <= '/') goto yy26;
		goto yy40;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy40;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy40;
			goto yy26;
		}
	}
yy38:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy40;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy40;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy40;
			goto yy26;
		}
	}
yy39:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy41;
		if (yych <= '/') goto yy26;
		goto yy42;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy42;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy42;
			goto yy26;
		}
	}
yy40:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy42;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy42;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy42;
			goto yy26;
		}
	}
yy41:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy43;
		if (yych <= '/') goto yy26;
		goto yy44;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy44;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy44;
			goto yy26;
		}
	}
yy42:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy44;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy44;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy44;
			goto yy26;
		}
	}
yy43:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy45;
		if (yych <= '/') goto yy26;
		goto yy46;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy46;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy46;
			goto yy26;
		}
	}
yy44:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy46;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy46;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy46;
			goto yy26;
		}
	}
yy45:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy47;
		if (yych <= '/') goto yy26;
		goto yy48;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy48;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy48;
			goto yy26;
		}
	}
yy46:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy48;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy48;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy48;
			goto yy26;
		}
	}
yy47:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy49;
		if (yych <= '/') goto yy26;
		goto yy50;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy50;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy50;
			goto yy26;
		}
	}
yy48:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy50;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy50;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy50;
			goto yy26;
		}
	}
yy49:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy51;
		if (yych <= '/') goto yy26;
		goto yy52;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy52;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy52;
			goto yy26;
		}
	}
yy50:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy52;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy52;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy52;
			goto yy26;
		}
	}
yy51:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy53;
		if (yych <= '/') goto yy26;
		goto yy54;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy54;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy54;
			goto yy26;
		}
	}
yy52:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy54;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy54;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy54;
			goto yy26;
		}
	}
yy53:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy55;
		if (yych <= '/') goto yy26;
		goto yy56;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy56;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy56;
			goto yy26;
		}
	}
yy54:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy56;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy56;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy56;
			goto yy26;
		}
	}
yy55:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy57;
		if (yych <= '/') goto yy26;
		goto yy58;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy58;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy58;
			goto yy26;
		}
	}
yy56:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy58;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy58;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy58;
			goto yy26;
		}
	}
yy57:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy59;
		if (yych <= '/') goto yy26;
		goto yy60;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy60;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy60;
			goto yy26;
		}
	}
yy58:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy60;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy60;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy60;
			goto yy26;
		}
	}
yy59:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy61;
		if (yych <= '/') goto yy26;
		goto yy62;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy62;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy62;
			goto yy26;
		}
	}
yy60:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy62;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy62;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy62;
			goto yy26;
		}
	}
yy61:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy63;
		if (yych <= '/') goto yy26;
		goto yy64;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy64;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy64;
			goto yy26;
		}
	}
yy62:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy64;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy64;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy64;
			goto yy26;
		}
	}
yy63:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy65;
		if (yych <= '/') goto yy26;
		goto yy66;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy66;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy66;
			goto yy26;
		}
	}
yy64:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy66;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy66;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy66;
			goto yy26;
		}
	}
yy65:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy67;
		if (yych <= '/') goto yy26;
		goto yy68;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy68;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy68;
			goto yy26;
		}
	}
yy66:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy68;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy68;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy68;
			goto yy26;
		}
	}
yy67:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy69;
		if (yych <= '/') goto yy26;
		goto yy70;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy70;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy70;
			goto yy26;
		}
	}
yy68:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy70;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy70;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy70;
			goto yy26;
		}
	}
yy69:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy71;
		if (yych <= '/') goto yy26;
		goto yy72;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy72;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy72;
			goto yy26;
		}
	}
yy70:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy72;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy72;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy72;
			goto yy26;
		}
	}
yy71:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy73;
		if (yych <= '/') goto yy26;
		goto yy74;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy74;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy74;
			goto yy26;
		}
	}
yy72:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy74;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy74;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy74;
			goto yy26;
		}
	}
yy73:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy75;
		if (yych <= '/') goto yy26;
		goto yy76;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy76;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy76;
			goto yy26;
		}
	}
yy74:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy76;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy76;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy76;
			goto yy26;
		}
	}
yy75:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy77;
		if (yych <= '/') goto yy26;
		goto yy78;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy78;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy78;
			goto yy26;
		}
	}
yy76:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy78;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy78;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy78;
			goto yy26;
		}
	}
yy77:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy79;
		if (yych <= '/') goto yy26;
		goto yy80;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy80;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy80;
			goto yy26;
		}
	}
yy78:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy80;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy80;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy80;
			goto yy26;
		}
	}
yy79:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy81;
		if (yych <= '/') goto yy26;
		goto yy82;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy82;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy82;
			goto yy26;
		}
	}
yy80:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy82;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy82;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy82;
			goto yy26;
		}
	}
yy81:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy83;
		if (yych <= '/') goto yy26;
		goto yy84;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy84;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy84;
			goto yy26;
		}
	}
yy82:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy84;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy84;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy84;
			goto yy26;
		}
	}
yy83:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy85;
		if (yych <= '/') goto yy26;
		goto yy86;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy86;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy86;
			goto yy26;
		}
	}
yy84:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy86;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy86;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy86;
			goto yy26;
		}
	}
yy85:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy87;
		if (yych <= '/') goto yy26;
		goto yy88;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy88;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy88;
			goto yy26;
		}
	}
yy86:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy88;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy88;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy88;
			goto yy26;
		}
	}
yy87:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy89;
		if (yych <= '/') goto yy26;
		goto yy90;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy90;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy90;
			goto yy26;
		}
	}
yy88:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy90;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy90;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy90;
			goto yy26;
		}
	}
yy89:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy91;
		if (yych <= '/') goto yy26;
		goto yy92;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy92;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy92;
			goto yy26;
		}
	}
yy90:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy92;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy92;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy92;
			goto yy26;
		}
	}
yy91:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy93;
		if (yych <= '/') goto yy26;
		goto yy94;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy94;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy94;
			goto yy26;
		}
	}
yy92:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy94;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy94;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy94;
			goto yy26;
		}
	}
yy93:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy95;
		if (yych <= '/') goto yy26;
		goto yy96;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy96;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy96;
			goto yy26;
		}
	}
yy94:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy96;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy96;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy96;
			goto yy26;
		}
	}
yy95:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy97;
		if (yych <= '/') goto yy26;
		goto yy98;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy98;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy98;
			goto yy26;
		}
	}
yy96:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy98;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy98;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy98;
			goto yy26;
		}
	}
yy97:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy99;
		if (yych <= '/') goto yy26;
		goto yy100;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy100;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy100;
			goto yy26;
		}
	}
yy98:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy100;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy100;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy100;
			goto yy26;
		}
	}
yy99:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy101;
		if (yych <= '/') goto yy26;
		goto yy102;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy102;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy102;
			goto yy26;
		}
	}
yy100:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy102;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy102;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy102;
			goto yy26;
		}
	}
yy101:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy103;
		if (yych <= '/') goto yy26;
		goto yy104;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy104;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy104;
			goto yy26;
		}
	}
yy102:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy104;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy104;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy104;
			goto yy26;
		}
	}
yy103:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy105;
		if (yych <= '/') goto yy26;
		goto yy106;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy106;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy106;
			goto yy26;
		}
	}
yy104:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy106;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy106;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy106;
			goto yy26;
		}
	}
yy105:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy107;
		if (yych <= '/') goto yy26;
		goto yy108;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy108;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy108;
			goto yy26;
		}
	}
yy106:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy108;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy108;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy108;
			goto yy26;
		}
	}
yy107:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy109;
		if (yych <= '/') goto yy26;
		goto yy110;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy110;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy110;
			goto yy26;
		}
	}
yy108:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy110;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy110;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy110;
			goto yy26;
		}
	}
yy109:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy111;
		if (yych <= '/') goto yy26;
		goto yy112;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy112;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy112;
			goto yy26;
		}
	}
yy110:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy112;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy112;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy112;
			goto yy26;
		}
	}
yy111:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy113;
		if (yych <= '/') goto yy26;
		goto yy114;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy114;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy114;
			goto yy26;
		}
	}
yy112:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy114;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy114;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy114;
			goto yy26;
		}
	}
yy113:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy115;
		if (yych <= '/') goto yy26;
		goto yy116;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy116;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy116;
			goto yy26;
		}
	}
yy114:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy116;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy116;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy116;
			goto yy26;
		}
	}
yy115:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy117;
		if (yych <= '/') goto yy26;
		goto yy118;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy118;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy118;
			goto yy26;
		}
	}
yy116:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy118;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy118;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy118;
			goto yy26;
		}
	}
yy117:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy119;
		if (yych <= '/') goto yy26;
		goto yy120;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy120;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy120;
			goto yy26;
		}
	}
yy118:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy120;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy120;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy120;
			goto yy26;
		}
	}
yy119:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy121;
		if (yych <= '/') goto yy26;
		goto yy122;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy122;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy122;
			goto yy26;
		}
	}
yy120:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy122;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy122;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy122;
			goto yy26;
		}
	}
yy121:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy123;
		if (yych <= '/') goto yy26;
		goto yy124;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy124;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy124;
			goto yy26;
		}
	}
yy122:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy124;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy124;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy124;
			goto yy26;
		}
	}
yy123:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy125;
		if (yych <= '/') goto yy26;
		goto yy126;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy126;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy126;
			goto yy26;
		}
	}
yy124:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy126;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy126;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy126;
			goto yy26;
		}
	}
yy125:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy127;
		if (yych <= '/') goto yy26;
		goto yy128;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy128;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy128;
			goto yy26;
		}
	}
yy126:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy128;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy128;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy128;
			goto yy26;
		}
	}
yy127:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy129;
		if (yych <= '/') goto yy26;
		goto yy130;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy130;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy130;
			goto yy26;
		}
	}
yy128:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy130;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy130;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy130;
			goto yy26;
		}
	}
yy129:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy131;
		if (yych <= '/') goto yy26;
		goto yy132;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy132;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy132;
			goto yy26;
		}
	}
yy130:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy132;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy132;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy132;
			goto yy26;
		}
	}
yy131:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy133;
		if (yych <= '/') goto yy26;
		goto yy134;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy134;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy134;
			goto yy26;
		}
	}
yy132:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy134;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy134;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy134;
			goto yy26;
		}
	}
yy133:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy135;
		if (yych <= '/') goto yy26;
		goto yy136;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy136;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy136;
			goto yy26;
		}
	}
yy134:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy136;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy136;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy136;
			goto yy26;
		}
	}
yy135:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy137;
		if (yych <= '/') goto yy26;
		goto yy138;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy138;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy138;
			goto yy26;
		}
	}
yy136:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy138;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy138;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy138;
			goto yy26;
		}
	}
yy137:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy139;
		if (yych <= '/') goto yy26;
		goto yy140;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy140;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy140;
			goto yy26;
		}
	}
yy138:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy140;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy140;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy140;
			goto yy26;
		}
	}
yy139:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy141;
		if (yych <= '/') goto yy26;
		goto yy142;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy142;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy142;
			goto yy26;
		}
	}
yy140:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy142;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy142;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy142;
			goto yy26;
		}
	}
yy141:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy143;
		if (yych <= '/') goto yy26;
		goto yy144;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy144;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy144;
			goto yy26;
		}
	}
yy142:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy144;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy144;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy144;
			goto yy26;
		}
	}
yy143:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy145;
		if (yych <= '/') goto yy26;
		goto yy146;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy146;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy146;
			goto yy26;
		}
	}
yy144:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy146;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy146;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy146;
			goto yy26;
		}
	}
yy145:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy147;
		if (yych <= '/') goto yy26;
		goto yy148;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy148;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy148;
			goto yy26;
		}
	}
yy146:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy148;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy148;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy148;
			goto yy26;
		}
	}
yy147:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '9') {
		if (yych == '-') goto yy149;
		if (yych <= '/') goto yy26;
		goto yy150;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy26;
			goto yy150;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy150;
			goto yy26;
		}
	}
yy148:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= ',') goto yy26;
			if (yych >= '.') goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych <= '9') goto yy150;
			goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
			goto yy150;
		} else {
			if (yych <= '`') goto yy26;
			if (yych <= 'z') goto yy150;
			goto yy26;
		}
	}
yy149:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '@') {
		if (yych <= '/') goto yy26;
		if (yych <= '9') goto yy151;
		goto yy26;
	} else {
		if (yych <= 'Z') goto yy151;
		if (yych <= '`') goto yy26;
		if (yych <= 'z') goto yy151;
		goto yy26;
	}
yy150:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych <= '=') {
		if (yych <= '.') {
			if (yych <= '-') goto yy26;
			goto yy27;
		} else {
			if (yych <= '/') goto yy26;
			if (yych >= ':') goto yy26;
		}
	} else {
		if (yych <= 'Z') {
			if (yych <= '>') goto yy30;
			if (yych <= '@') goto yy26;
		} else {
			if (yych <= '`') goto yy26;
			if (yych >= '{') goto yy26;
		}
	}
yy151:
	++p;
	yych = (p < length ? input[p] : 0);
	if (yych == '.') goto yy27;
	if (yych == '>') goto yy30;
	goto yy26;
}

}
