#ifndef MARKDOWN_CORE_EXT_EMPHASIS_H
#define MARKDOWN_CORE_EXT_EMPHASIS_H
#include "extension.h"
extern const markdown_core_extension MARKDOWN_CORE_EXTENSION_EMPHASIS;
extern const markdown_core_extension MARKDOWN_CORE_EXTENSION_EMPHASIS_UNDERSCORE;
#endif
