/* Generated by re2c 4.5.1 */

#include "ext_scanners.h"
#include <stdlib.h>

bufsize_t _ext_scan_at(bufsize_t (*scanner)(const unsigned char *),
                       unsigned char *ptr, int len, bufsize_t offset) {
  bufsize_t res;

  if (ptr == NULL || offset >= len) {
    return 0;
  } else {
    unsigned char lim = ptr[len];

    ptr[len] = '\0';
    res = scanner(ptr + offset);
    ptr[len] = lim;
  }

  return res;
}
bufsize_t _scan_table_start(const unsigned char *p) {
  const unsigned char *marker = NULL;
  const unsigned char *start = p;

  {
    unsigned char yych;
    static const unsigned char yybm[256] = {
        0, 0,   0, 0, 0, 0, 0, 0, 0, 64, 0,  64, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  64, 0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 128, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0};
    yych = *p;
    if (yych <= ' ') {
      if (yych <= '\n') {
        if (yych == '\t')
          goto yy2;
      } else {
        if (yych <= '\f')
          goto yy2;
        if (yych >= ' ')
          goto yy2;
      }
    } else {
      if (yych <= '9') {
        if (yych == '-')
          goto yy3;
      } else {
        if (yych <= ':')
          goto yy4;
        if (yych == '|')
          goto yy2;
      }
    }
    ++p;
  yy1: { return 0; }
  yy2:
    yych = *(marker = ++p);
    if (yybm[0 + yych] & 64)
      goto yy5;
    if (yych == '-')
      goto yy7;
    if (yych == ':')
      goto yy8;
    goto yy1;
  yy3:
    yych = *(marker = ++p);
    if (yybm[0 + yych] & 128)
      goto yy7;
    if (yych <= ' ') {
      if (yych <= 0x08)
        goto yy1;
      if (yych <= '\r')
        goto yy10;
      if (yych <= 0x1F)
        goto yy1;
      goto yy10;
    } else {
      if (yych <= ':') {
        if (yych <= '9')
          goto yy1;
        goto yy9;
      } else {
        if (yych == '|')
          goto yy10;
        goto yy1;
      }
    }
  yy4:
    yych = *(marker = ++p);
    if (yybm[0 + yych] & 128)
      goto yy7;
    goto yy1;
  yy5:
    yych = *++p;
    if (yybm[0 + yych] & 64)
      goto yy5;
    if (yych == '-')
      goto yy7;
    if (yych == ':')
      goto yy8;
  yy6:
    p = marker;
    goto yy1;
  yy7:
    yych = *++p;
    if (yybm[0 + yych] & 128)
      goto yy7;
    if (yych <= 0x1F) {
      if (yych <= '\n') {
        if (yych <= 0x08)
          goto yy6;
        if (yych <= '\t')
          goto yy9;
        goto yy11;
      } else {
        if (yych <= '\f')
          goto yy9;
        if (yych <= '\r')
          goto yy12;
        goto yy6;
      }
    } else {
      if (yych <= ':') {
        if (yych <= ' ')
          goto yy9;
        if (yych <= '9')
          goto yy6;
        goto yy9;
      } else {
        if (yych == '|')
          goto yy13;
        goto yy6;
      }
    }
  yy8:
    yych = *++p;
    if (yybm[0 + yych] & 128)
      goto yy7;
    goto yy6;
  yy9:
    yych = *++p;
  yy10:
    if (yych <= '\r') {
      if (yych <= '\t') {
        if (yych <= 0x08)
          goto yy6;
        goto yy9;
      } else {
        if (yych <= '\n')
          goto yy11;
        if (yych <= '\f')
          goto yy9;
        goto yy12;
      }
    } else {
      if (yych <= ' ') {
        if (yych <= 0x1F)
          goto yy6;
        goto yy9;
      } else {
        if (yych == '|')
          goto yy13;
        goto yy6;
      }
    }
  yy11:
    ++p;
    {
      return (bufsize_t)(p - start);
    }
  yy12:
    yych = *++p;
    if (yych == '\n')
      goto yy11;
    goto yy6;
  yy13:
    yych = *++p;
    if (yybm[0 + yych] & 128)
      goto yy7;
    if (yych <= '\r') {
      if (yych <= '\t') {
        if (yych <= 0x08)
          goto yy6;
        goto yy13;
      } else {
        if (yych <= '\n')
          goto yy11;
        if (yych <= '\f')
          goto yy13;
        goto yy12;
      }
    } else {
      if (yych <= ' ') {
        if (yych <= 0x1F)
          goto yy6;
        goto yy13;
      } else {
        if (yych == ':')
          goto yy8;
        goto yy6;
      }
    }
  }
}

bufsize_t _scan_table_cell(const unsigned char *p) {
  const unsigned char *marker = NULL;
  const unsigned char *start = p;

  {
    unsigned char yych;
    unsigned int yyaccept = 0;
    static const unsigned char yybm[256] = {
        0,  64, 64,  64, 64, 64, 64, 64, 64, 64, 0,  64, 64, 0,  64, 64, 64, 64,
        64, 64, 64,  64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
        64, 64, 64,  64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
        64, 64, 64,  64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
        64, 64, 64,  64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
        64, 64, 128, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
        64, 64, 64,  64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 0,  64,
        64, 64, 0,   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,   0};
    yych = *p;
    if (yybm[0 + yych] & 64)
      goto yy17;
    if (yych <= 0xEC) {
      if (yych <= 0xC1) {
        if (yych <= '\r')
          goto yy15;
        if (yych <= '\\')
          goto yy19;
      } else {
        if (yych <= 0xDF)
          goto yy20;
        if (yych <= 0xE0)
          goto yy21;
        goto yy22;
      }
    } else {
      if (yych <= 0xF0) {
        if (yych <= 0xED)
          goto yy23;
        if (yych <= 0xEF)
          goto yy22;
        goto yy24;
      } else {
        if (yych <= 0xF3)
          goto yy25;
        if (yych <= 0xF4)
          goto yy26;
      }
    }
  yy15:
    ++p;
  yy16: { return 0; }
  yy17:
    yyaccept = 0;
    yych = *(marker = ++p);
    if (yybm[0 + yych] & 64)
      goto yy17;
    if (yych <= 0xEC) {
      if (yych <= 0xC1) {
        if (yych <= '\r')
          goto yy18;
        if (yych <= '\\')
          goto yy19;
      } else {
        if (yych <= 0xDF)
          goto yy27;
        if (yych <= 0xE0)
          goto yy29;
        goto yy30;
      }
    } else {
      if (yych <= 0xF0) {
        if (yych <= 0xED)
          goto yy31;
        if (yych <= 0xEF)
          goto yy30;
        goto yy32;
      } else {
        if (yych <= 0xF3)
          goto yy33;
        if (yych <= 0xF4)
          goto yy34;
      }
    }
  yy18: { return (bufsize_t)(p - start); }
  yy19:
    yyaccept = 0;
    yych = *(marker = ++p);
    if (yybm[0 + yych] & 128)
      goto yy19;
    if (yych <= 0xDF) {
      if (yych <= '\f') {
        if (yych <= 0x00)
          goto yy18;
        if (yych == '\n')
          goto yy18;
        goto yy17;
      } else {
        if (yych <= '\r')
          goto yy18;
        if (yych <= 0x7F)
          goto yy17;
        if (yych <= 0xC1)
          goto yy18;
        goto yy27;
      }
    } else {
      if (yych <= 0xEF) {
        if (yych <= 0xE0)
          goto yy29;
        if (yych == 0xED)
          goto yy31;
        goto yy30;
      } else {
        if (yych <= 0xF0)
          goto yy32;
        if (yych <= 0xF3)
          goto yy33;
        if (yych <= 0xF4)
          goto yy34;
        goto yy18;
      }
    }
  yy20:
    yych = *++p;
    if (yych <= 0x7F)
      goto yy16;
    if (yych <= 0xBF)
      goto yy17;
    goto yy16;
  yy21:
    yyaccept = 1;
    yych = *(marker = ++p);
    if (yych <= 0x9F)
      goto yy16;
    if (yych <= 0xBF)
      goto yy27;
    goto yy16;
  yy22:
    yyaccept = 1;
    yych = *(marker = ++p);
    if (yych <= 0x7F)
      goto yy16;
    if (yych <= 0xBF)
      goto yy27;
    goto yy16;
  yy23:
    yyaccept = 1;
    yych = *(marker = ++p);
    if (yych <= 0x7F)
      goto yy16;
    if (yych <= 0x9F)
      goto yy27;
    goto yy16;
  yy24:
    yyaccept = 1;
    yych = *(marker = ++p);
    if (yych <= 0x8F)
      goto yy16;
    if (yych <= 0xBF)
      goto yy30;
    goto yy16;
  yy25:
    yyaccept = 1;
    yych = *(marker = ++p);
    if (yych <= 0x7F)
      goto yy16;
    if (yych <= 0xBF)
      goto yy30;
    goto yy16;
  yy26:
    yyaccept = 1;
    yych = *(marker = ++p);
    if (yych <= 0x7F)
      goto yy16;
    if (yych <= 0x8F)
      goto yy30;
    goto yy16;
  yy27:
    yych = *++p;
    if (yych <= 0x7F)
      goto yy28;
    if (yych <= 0xBF)
      goto yy17;
  yy28:
    p = marker;
    if (yyaccept == 0)
      goto yy18;
    else
      goto yy16;
  yy29:
    yych = *++p;
    if (yych <= 0x9F)
      goto yy28;
    if (yych <= 0xBF)
      goto yy27;
    goto yy28;
  yy30:
    yych = *++p;
    if (yych <= 0x7F)
      goto yy28;
    if (yych <= 0xBF)
      goto yy27;
    goto yy28;
  yy31:
    yych = *++p;
    if (yych <= 0x7F)
      goto yy28;
    if (yych <= 0x9F)
      goto yy27;
    goto yy28;
  yy32:
    yych = *++p;
    if (yych <= 0x8F)
      goto yy28;
    if (yych <= 0xBF)
      goto yy30;
    goto yy28;
  yy33:
    yych = *++p;
    if (yych <= 0x7F)
      goto yy28;
    if (yych <= 0xBF)
      goto yy30;
    goto yy28;
  yy34:
    yych = *++p;
    if (yych <= 0x7F)
      goto yy28;
    if (yych <= 0x8F)
      goto yy30;
    goto yy28;
  }
}

bufsize_t _scan_table_cell_end(const unsigned char *p) {
  const unsigned char *start = p;

  {
    unsigned char yych;
    static const unsigned char yybm[256] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 128, 128, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   128, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0};
    yych = *p;
    if (yych == '|')
      goto yy36;
    ++p;
    {
      return 0;
    }
  yy36:
    yych = *++p;
    if (yybm[0 + yych] & 128)
      goto yy36;
    {
      return (bufsize_t)(p - start);
    }
  }
}

bufsize_t _scan_table_row_end(const unsigned char *p) {
  const unsigned char *marker = NULL;
  const unsigned char *start = p;

  {
    unsigned char yych;
    static const unsigned char yybm[256] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 128, 128, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   128, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0};
    yych = *p;
    if (yych <= '\f') {
      if (yych <= 0x08)
        goto yy38;
      if (yych == '\n')
        goto yy41;
      goto yy40;
    } else {
      if (yych <= '\r')
        goto yy42;
      if (yych == ' ')
        goto yy40;
    }
  yy38:
    ++p;
  yy39: { return 0; }
  yy40:
    yych = *(marker = ++p);
    if (yych <= 0x08)
      goto yy39;
    if (yych <= '\r')
      goto yy44;
    if (yych == ' ')
      goto yy44;
    goto yy39;
  yy41:
    ++p;
    {
      return (bufsize_t)(p - start);
    }
  yy42:
    yych = *++p;
    if (yych == '\n')
      goto yy41;
    goto yy39;
  yy43:
    yych = *++p;
  yy44:
    if (yybm[0 + yych] & 128)
      goto yy43;
    if (yych <= 0x08)
      goto yy45;
    if (yych <= '\n')
      goto yy41;
    if (yych <= '\r')
      goto yy46;
  yy45:
    p = marker;
    goto yy39;
  yy46:
    yych = *++p;
    if (yych == '\n')
      goto yy41;
    goto yy45;
  }
}

bufsize_t _scan_tasklist(const unsigned char *p) {
  const unsigned char *marker = NULL;
  const unsigned char *start = p;

  {
    unsigned char yych;
    static const unsigned char yybm[256] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 128, 128, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   128, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0,   0,   0, 0, 0};
    yych = *p;
    if (yych == '[')
      goto yy49;
    ++p;
  yy48: { return 0; }
  yy49:
    yych = *(marker = ++p);
    if (yych <= 'W') {
      if (yych != ' ')
        goto yy48;
    } else {
      if (yych <= 'X')
        goto yy50;
      if (yych != 'x')
        goto yy48;
    }
  yy50:
    yych = *++p;
    if (yych == ']')
      goto yy52;
  yy51:
    p = marker;
    goto yy48;
  yy52:
    yych = *++p;
    if (yybm[0 + yych] & 128)
      goto yy53;
    goto yy51;
  yy53:
    yych = *++p;
    if (yybm[0 + yych] & 128)
      goto yy53;
    {
      return (bufsize_t)(p - start);
    }
  }
}

bufsize_t _scan_formula_dollar_inline_open(const unsigned char *p) {
  const unsigned char *start = p;

  {
    unsigned char yych;
    yych = *p;
    if (yych == '$')
      goto yy55;
    ++p;
    {
      return 0;
    }
  yy55:
    ++p;
    {
      return (bufsize_t)(p - start);
    }
  }
}

bufsize_t _scan_formula_dollar_backtick_open(const unsigned char *p) {
  const unsigned char *start = p;

  {
    unsigned char yych;
    yych = *p;
    if (yych == '$')
      goto yy58;
    ++p;
  yy57: { return 0; }
  yy58:
    yych = *++p;
    if (yych != '`')
      goto yy57;
    ++p;
    {
      return (bufsize_t)(p - start);
    }
  }
}

bufsize_t _scan_formula_dollar_display_open(const unsigned char *p) {
  const unsigned char *start = p;

  {
    unsigned char yych;
    yych = *p;
    if (yych == '$')
      goto yy61;
    ++p;
  yy60: { return 0; }
  yy61:
    yych = *++p;
    if (yych != '$')
      goto yy60;
    ++p;
    {
      return (bufsize_t)(p - start);
    }
  }
}

bufsize_t _scan_formula_latex_backslash_inline_open(const unsigned char *p) {
  const unsigned char *marker = NULL;
  const unsigned char *start = p;

  {
    unsigned char yych;
    yych = *p;
    if (yych == '\\')
      goto yy64;
    ++p;
  yy63: { return 0; }
  yy64:
    yych = *(marker = ++p);
    if (yych != '\\')
      goto yy63;
    yych = *++p;
    if (yych == '(')
      goto yy65;
    p = marker;
    goto yy63;
  yy65:
    ++p;
    {
      return (bufsize_t)(p - start);
    }
  }
}

bufsize_t _scan_formula_latex_backslash_display_open(const unsigned char *p) {
  const unsigned char *marker = NULL;
  const unsigned char *start = p;

  {
    unsigned char yych;
    yych = *p;
    if (yych == '\\')
      goto yy68;
    ++p;
  yy67: { return 0; }
  yy68:
    yych = *(marker = ++p);
    if (yych != '\\')
      goto yy67;
    yych = *++p;
    if (yych == '[')
      goto yy69;
    p = marker;
    goto yy67;
  yy69:
    ++p;
    {
      return (bufsize_t)(p - start);
    }
  }
}

bufsize_t _scan_directive_name(const unsigned char *p) {
  const unsigned char *start = p;

  {
    unsigned char yych;
    static const unsigned char yybm[256] = {
        0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        0,   0,   0,   128, 0,   0,   128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 0,   0,   0,   0,   0,   0,   0,   128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 0,   0,   0,   0,   128, 0,   128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128,
        128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 0,   0,   0,
        0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        0,   0,   0,   0};
    yych = *p;
    if (yybm[0 + yych] & 128)
      goto yy71;
    ++p;
    {
      return 0;
    }
  yy71:
    yych = *++p;
    if (yybm[0 + yych] & 128)
      goto yy71;
    {
      return (bufsize_t)(p - start);
    }
  }
}
