#ifndef MARKDOWN_CORE_NODE_TYPE_H
#define MARKDOWN_CORE_NODE_TYPE_H

#ifdef __cplusplus
extern "C" {
#endif

/* A node's internal type: a class bit pair and a per-class value. The public
 * facade reports a node through `markdown_core_node_kind` instead, which the
 * generated tables in ast.c map these onto. */

#define MARKDOWN_CORE_NODE_TYPE_PRESENT (0x8000)
#define MARKDOWN_CORE_NODE_TYPE_BLOCK (MARKDOWN_CORE_NODE_TYPE_PRESENT | 0x0000)
#define MARKDOWN_CORE_NODE_TYPE_INLINE (MARKDOWN_CORE_NODE_TYPE_PRESENT | 0x4000)
#define MARKDOWN_CORE_NODE_TYPE_MASK (0xc000)
#define MARKDOWN_CORE_NODE_VALUE_MASK (0x3fff)

/* BEGIN GENERATED by scripts/tooling/generate-node-kinds.mjs; edit the node-kind schemas instead. */
/* One past the largest value either class uses, so `kind & VALUE_MASK` is a
 * dense index into a per-class table. */
#define MARKDOWN_CORE_NODE_KIND_COUNT (0x0018)

typedef enum {
    /* Error status */
    MARKDOWN_CORE_NODE_NONE = 0x0000,

    /* Block */
    MARKDOWN_CORE_NODE_DOCUMENT = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x0001,
    MARKDOWN_CORE_NODE_CALLOUT = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x0002,
    MARKDOWN_CORE_NODE_LIST = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x0003,
    MARKDOWN_CORE_NODE_LIST_ITEM = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x0004,
    MARKDOWN_CORE_NODE_CODE_BLOCK = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x0005,
    MARKDOWN_CORE_NODE_HTML_BLOCK = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x0006,
    MARKDOWN_CORE_NODE_PARAGRAPH = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x0007,
    MARKDOWN_CORE_NODE_HEADING = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x0008,
    MARKDOWN_CORE_NODE_THEMATIC_BREAK = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x0009,
    /* A footnote definition: a block container while it is parsed, and a
     * document-owned Footnote value once the document finalizes, when every one
     * leaves the tree for the root's own footnote chain. */
    MARKDOWN_CORE_NODE_FOOTNOTE = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x000a,
    /* Its payload comes from the table element's opaque_alloc_func. */
    MARKDOWN_CORE_NODE_TABLE = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x000b,
    MARKDOWN_CORE_NODE_TABLE_ROW = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x000c,
    MARKDOWN_CORE_NODE_TABLE_CELL = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x000d,
    /* Its payload comes from the formula element's opaque_alloc_func. */
    MARKDOWN_CORE_NODE_FORMULA_BLOCK = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x000e,
    /* Its payload comes from the directive element's opaque_alloc_func. */
    MARKDOWN_CORE_NODE_DIRECTIVE_BLOCK = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x000f,
    /* A block comment: an HTML block that opened with <!-- and whose end line
     * held only whitespace after the first -->. One public kind, Comment,
     * stands for this and for the inline COMMENT; the two internal types record
     * which content the node sits in, which is what containment checks and the
     * inline parser ask. */
    MARKDOWN_CORE_NODE_COMMENT_BLOCK = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x0010,
    /* A specimen definition: a document-owned citation value. */
    MARKDOWN_CORE_NODE_SPECIMEN = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x0011,
    MARKDOWN_CORE_NODE_DEFINITION_LIST = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x0012,
    MARKDOWN_CORE_NODE_DEFINITION = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x0013,
    /* A private collection root, not a public Markup kind. */
    MARKDOWN_CORE_NODE_DEFINITION_BODY = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x0014,
    MARKDOWN_CORE_NODE_TABLE_CAPTION = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x0015,
    /* Read by the document element's prefix reader (properties.c) and never
     * parsed as a block, so no element defines its structure. */
    MARKDOWN_CORE_NODE_METADATA = MARKDOWN_CORE_NODE_TYPE_BLOCK | 0x0016,

    /* Inline */
    MARKDOWN_CORE_NODE_TEXT = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0001,
    MARKDOWN_CORE_NODE_SOFT_BREAK = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0002,
    MARKDOWN_CORE_NODE_LINE_BREAK = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0003,
    MARKDOWN_CORE_NODE_CODE = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0004,
    MARKDOWN_CORE_NODE_HTML = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0005,
    MARKDOWN_CORE_NODE_EMPHASIS = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0006,
    MARKDOWN_CORE_NODE_STRONG = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0007,
    MARKDOWN_CORE_NODE_LINK = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0008,
    MARKDOWN_CORE_NODE_EMBEDDED = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0009,
    /* A citation cluster, whose items are a chain of CITATION nodes it owns
     * beside its children, which it never has. */
    MARKDOWN_CORE_NODE_CITE = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x000a,
    MARKDOWN_CORE_NODE_STRIKETHROUGH = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x000b,
    /* Its payload comes from the formula element's opaque_alloc_func. */
    MARKDOWN_CORE_NODE_FORMULA = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x000c,
    /* Its payload comes from the directive element's opaque_alloc_func. */
    MARKDOWN_CORE_NODE_DIRECTIVE = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x000d,
    MARKDOWN_CORE_NODE_DIRECTIVE_LABEL = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x000e,
    /* An inline HTML comment token: <!-- ... -->, <!--> or <!--->. */
    MARKDOWN_CORE_NODE_COMMENT = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x000f,
    /* One item of a Cite: a scoped value, never a child of anything, owning a
     * prefix chain and a suffix chain of inline nodes beside its referent.
     * Inline-classed because it lives in inline content. */
    MARKDOWN_CORE_NODE_CITATION = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0010,
    MARKDOWN_CORE_NODE_CROSS_LINK = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0011,
    MARKDOWN_CORE_NODE_MARK = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0012,
    MARKDOWN_CORE_NODE_CROSS_EMBEDDED = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0013,
    MARKDOWN_CORE_NODE_INSERTION = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0014,
    /* Built by the link element's bracket closer when a bracket matches no
     * link; it takes no structure hooks from any element. */
    MARKDOWN_CORE_NODE_SPAN = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0015,
    MARKDOWN_CORE_NODE_SUPERSCRIPT = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0016,
    MARKDOWN_CORE_NODE_SUBSCRIPT = MARKDOWN_CORE_NODE_TYPE_INLINE | 0x0017,
} markdown_core_node_type;
/* END GENERATED */

#ifndef MARKDOWN_CORE_NODE_TYPEDEF
#define MARKDOWN_CORE_NODE_TYPEDEF
typedef struct markdown_core_node markdown_core_node;
#endif

#ifdef __cplusplus
}
#endif

#endif
