// One extension pair per stored kind: how its fields are projected from the
// record that holds them, and how a view over the record is made from an
// index. Both are tag checks on the enum, never runtime casts. Generated by
// hand from the kind inventory the AST projection audit checks.

extension Document.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .document(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Document")
    }
}

extension Document: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Document {
        Document(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Callout.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .callout(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Callout")
    }
}

extension Callout: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Callout {
        Callout(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Paragraph.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .paragraph(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Paragraph")
    }
}

extension Paragraph: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Paragraph {
        Paragraph(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Heading.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .heading(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Heading")
    }
}

extension Heading: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Heading {
        Heading(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension List.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .list(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for List")
    }
}

extension List: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> List {
        List(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension ListItem.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .listItem(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for ListItem")
    }
}

extension ListItem: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> ListItem {
        ListItem(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Table.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .table(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Table")
    }
}

extension Table: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Table {
        Table(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension TableCaption.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .tableCaption(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for TableCaption")
    }
}

extension TableCaption: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> TableCaption {
        TableCaption(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension TableRow.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .tableRow(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for TableRow")
    }
}

extension TableRow: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> TableRow {
        TableRow(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension TableCell.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .tableCell(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for TableCell")
    }
}

extension TableCell: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> TableCell {
        TableCell(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension DirectiveBlock.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .directiveBlock(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for DirectiveBlock")
    }
}

extension DirectiveBlock: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> DirectiveBlock {
        DirectiveBlock(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension DirectiveLabel.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .directiveLabel(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for DirectiveLabel")
    }
}

extension DirectiveLabel: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> DirectiveLabel {
        DirectiveLabel(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Emphasis.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .emphasis(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Emphasis")
    }
}

extension Emphasis: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Emphasis {
        Emphasis(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Strong.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .strong(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Strong")
    }
}

extension Strong: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Strong {
        Strong(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Strikethrough.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .strikethrough(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Strikethrough")
    }
}

extension Strikethrough: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Strikethrough {
        Strikethrough(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Mark.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .mark(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Mark")
    }
}

extension Mark: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Mark {
        Mark(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Insertion.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .insertion(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Insertion")
    }
}

extension Insertion: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Insertion {
        Insertion(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Span.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .span(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Span")
    }
}

extension Span: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Span {
        Span(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Superscript.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .superscript(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Superscript")
    }
}

extension Superscript: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Superscript {
        Superscript(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Subscript.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .`subscript`(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Subscript")
    }
}

extension Subscript: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Subscript {
        Subscript(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Link.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .link(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Link")
    }
}

extension Link: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Link {
        Link(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}
