// One extension pair per stored kind: how its fields are projected from the
// record that holds them, and how a view over the record is made from an
// index. Both are tag checks on the enum, never runtime casts. Generated by
// hand from the kind inventory the AST projection audit checks.

extension Embedded.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .embedded(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Embedded")
    }
}

extension Embedded: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Embedded {
        Embedded(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Directive.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .directive(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Directive")
    }
}

extension Directive: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Directive {
        Directive(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Cite.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .cite(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Cite")
    }
}

extension Cite: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Cite {
        Cite(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension DefinitionList.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .definitionList(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for DefinitionList")
    }
}

extension DefinitionList: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> DefinitionList {
        DefinitionList(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Definition.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .definition(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Definition")
    }
}

extension Definition: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Definition {
        Definition(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Citation.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .citation(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Citation")
    }
}

extension Citation: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Citation {
        Citation(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Footnote.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .footnote(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Footnote")
    }
}

extension Footnote: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Footnote {
        Footnote(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Specimen.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .specimen(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Specimen")
    }
}

extension Specimen: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Specimen {
        Specimen(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension ThematicBreak.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .thematicBreak(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for ThematicBreak")
    }
}

extension ThematicBreak: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> ThematicBreak {
        ThematicBreak(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension CodeBlock.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .codeBlock(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for CodeBlock")
    }
}

extension CodeBlock: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> CodeBlock {
        CodeBlock(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension HTMLBlock.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .htmlBlock(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for HTMLBlock")
    }
}

extension HTMLBlock: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> HTMLBlock {
        HTMLBlock(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension FormulaBlock.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .formulaBlock(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for FormulaBlock")
    }
}

extension FormulaBlock: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> FormulaBlock {
        FormulaBlock(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Text.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .text(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Text")
    }
}

extension Text: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Text {
        Text(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension SoftBreak.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .softBreak(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for SoftBreak")
    }
}

extension SoftBreak: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> SoftBreak {
        SoftBreak(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension LineBreak.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .lineBreak(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for LineBreak")
    }
}

extension LineBreak: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> LineBreak {
        LineBreak(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Code.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .code(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Code")
    }
}

extension Code: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Code {
        Code(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension HTML.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .html(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for HTML")
    }
}

extension HTML: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> HTML {
        HTML(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension CrossLink.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .crossLink(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for CrossLink")
    }
}

extension CrossLink: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> CrossLink {
        CrossLink(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension CrossEmbedded.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .crossEmbedded(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for CrossEmbedded")
    }
}

extension CrossEmbedded: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> CrossEmbedded {
        CrossEmbedded(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Comment.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .comment(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Comment")
    }
}

extension Comment: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Comment {
        Comment(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Formula.Fields: StoredFields {
    static func project(_ record: StoredMarkup) -> Self {
        if case let .formula(fields) = record { return fields }
        preconditionFailure("Invalid stored fields for Formula")
    }
}

extension Formula: MarkupElement, StoredMarkupView {
    static func stored(at index: Int, in store: MarkupStore) -> Formula {
        Formula(fields: Stored(store: store, index: index))
    }

    var storedLocation: StoredLocation { fields.location }
}

extension Metadata: MarkupElement {
    static func stored(at index: Int, in store: MarkupStore) -> Metadata {
        if case let .metadata(node) = store.records[index] { return node }
        preconditionFailure("Invalid stored fields for Metadata")
    }
}
